In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [ ]:
list_angka = [5,6,7]

In [ ]:
list_angka * 2

[5, 6, 7, 5, 6, 7]

In [ ]:
np.array(list_angka) * 2

array([10, 12, 14])

In [ ]:
list_angka = [[1,2,3], [4,5,6]]
print(list_angka)
list_angka * 2

[[1, 2, 3], [4, 5, 6]]


[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [ ]:
np.array(list_angka) * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

# Cara buat Numpy array
- np.array()
- np.zeros() buat numpy array isinya angka 0 semua
- np.ones() buat numpy array isinya angka 1 semua
- np.empty() isinya kita tidak tau, tergantung memory computer nya
- np.arange() angka urut
- np.random.random() isinya random antara 0-1

In [ ]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
a = np.zeros(5)
print(a)
print(type(a))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [ ]:
a = np.ones(5)
print(a)
print(type(a))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
a = np.empty(5) #harus asumsikan isinya kosong/ tidak tau
print(a)
print(type(a))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
a = np.arange(5)
print(a)
print(type(a))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
np.arange(5,10).reshape(5,1)

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
np.arange(5,100,25)

array([ 5, 30, 55, 80])

In [ ]:
np.random.random(10)


array([0.69529728, 0.40215416, 0.91270756, 0.33520438, 0.597788  ,
       0.61096139, 0.45505389, 0.615892  , 0.50813609, 0.04845578])

In [ ]:
np.random.random(10)

array([0.62642529, 0.76006143, 0.04347701, 0.10781696, 0.01358771,
       0.55719553, 0.51216781, 0.86356729, 0.43565102, 0.67154047])

In [ ]:
(np.random.random((2,5)) * 6 + 1 ).astype(int)

array([[5, 5, 4, 6, 3],
       [1, 2, 6, 4, 5]])

In [ ]:
np.ones((2,5)) * 8

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

# Edit Numpy array
- add, append
- remove, delete
- sort

In [ ]:
a = np.array([3,4,5])
b = np.array([9,10,11])

In [ ]:
# append
ab = np.append(a,b) # membuat array baru

In [ ]:
np.append(a, [1]) # membuat array baru

array([3, 4, 5, 1])

In [ ]:
print(a)

[3 4 5]


In [ ]:
np.append(a, [6])

array([3, 4, 5, 6])

In [ ]:
print(ab)

[ 3  4  5  9 10 11]


In [ ]:
# delete
ab_deleted = np.delete(ab, -1) # membuat array baru
print(ab_deleted)

[ 3  4  5  9 10]


In [ ]:
print(ab) 

[ 3  4  5  9 10 11]


In [ ]:
# sort
c = np.array([5,-5,10,-10,50,-50])
print(c)

[  5  -5  10 -10  50 -50]


In [ ]:
np.sort(c)

array([-50, -10,  -5,   5,  10,  50])

In [ ]:
print (c)

[  5  -5  10 -10  50 -50]


# Melihat bentuk dan ukuran Numpy array
- shape (bentuknya)
- size (ukurannya, berapa jumlah item yang ada di dalam)

In [ ]:
a = np.array([100,200,300,400,500])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[100 200 300 400 500]
(5,)
1
5


In [ ]:
a = np.array([[100,200,300,400,500]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[100 200 300 400 500]]
(1, 5)
2
5


In [ ]:
a = np.array([
    [100,200, 3],
    [300,400, 5]
])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[100 200   3]
 [300 400   5]]
(2, 3)
2
6


# reshape
kita sudah bisa membuat, edit, dan melihat bentuk sebuah numpy array. berikutnya adalah mengubah bentuk numpy array. dari 1d jadi 2d, 2d jadi 1d, dan lainnya

In [ ]:
a = np.array([
    [100,200, 3],
    [300,400, 5]
])
print(a)
print(a.shape)

[[100 200   3]
 [300 400   5]]
(2, 3)


In [ ]:
a.reshape((6,1))

array([[100],
       [200],
       [  3],
       [300],
       [400],
       [  5]])

In [ ]:
a.reshape((6,))

array([100, 200,   3, 300, 400,   5])

In [ ]:
b = a.reshape((6,1,1)) # membuat array baru
print(b)

[[[100]]

 [[200]]

 [[  3]]

 [[300]]

 [[400]]

 [[  5]]]


In [ ]:
print(a) # a nya sendiri tidak diubah

[[100 200   3]
 [300 400   5]]


# nambah dimensi
- np.newaxis
- np.expand_dims

In [ ]:
a = np.array([100,200, 3,300,400, 5])
print(a.shape)
print(a.ndim)

(6,)
1


In [ ]:
b = a[np.newaxis]
print(b)
print(b.shape)
print(b.ndim)

[[100 200   3 300 400   5]]
(1, 6)
2


In [ ]:
b = a[:, np.newaxis]
print(b)
print(b.shape)
print(b.ndim)

[[100]
 [200]
 [  3]
 [300]
 [400]
 [  5]]
(6, 1)
2


In [ ]:
b = np.expand_dims(a, axis=0)
print(b)
print(b.shape)
print(b.ndim)

[[100 200   3 300 400   5]]
(1, 6)
2


In [ ]:
b = np.expand_dims(a, axis=1)
print(b)
print(b.shape)
print(b.ndim)

[[100]
 [200]
 [  3]
 [300]
 [400]
 [  5]]
(6, 1)
2


# Indexing and Slicing
- indexing: ambil 1 item dari array
- slicing: ambil bbrp item dari array

In [ ]:
a = np.array([100,200, 3,300,400, 5])
b = a.reshape(2,3)
print(b)

[[100 200   3]
 [300 400   5]]


In [ ]:
b[0]

array([100, 200,   3])

In [ ]:
# indexing
b[0,0]

100

In [ ]:
b[1, 2]

5

In [ ]:
# slicing
b[0, 1:]

array([200,   3])

In [ ]:
b[:, 1:]

array([[200,   3],
       [400,   5]])

In [ ]:
b[:, 1]

array([200, 400])

In [ ]:
# kondisi
print(b)

[[100 200   3]
 [300 400   5]]


In [ ]:
b[b>100]

array([200, 300, 400])

In [ ]:
b[b<10]

array([3, 5])

In [ ]:
b[b%2 == 0]

array([100, 200, 300, 400])

In [ ]:
b[(b%2 == 0) & (b > 200)]

array([300, 400])

In [ ]:
b[(b%2 == 0) | (b < 10)]

array([100, 200,   3, 300, 400,   5])

# stack, split, copy

In [ ]:
a = np.array([100,200, 3,300,400, 5])
b = a.reshape(2,3)
c = np.array([[10,15],[20,21]])
print(b)
print(c)

[[100 200   3]
 [300 400   5]]
[[10 15]
 [20 21]]


In [ ]:
print(b.shape)
print(c.shape)

(2, 3)
(2, 2)


In [ ]:
# hstack
d = np.hstack((b,c))
print(d)
print(d.shape)

[[100 200   3  10  15]
 [300 400   5  20  21]]
(2, 5)


In [ ]:
d = np.hstack((c, b))
print(d)
print(d.shape)

[[ 10  15 100 200   3]
 [ 20  21 300 400   5]]
(2, 5)


In [ ]:
# vstack
c2 = np.arange(3).reshape(1,3)
print(c2)
print(c2.shape)

[[0 1 2]]
(1, 3)


In [ ]:
print(b)
print(b.shape)

[[100 200   3]
 [300 400   5]]
(2, 3)


In [ ]:
d = np.vstack((b,c2))
print(d)
print(d.shape)

[[100 200   3]
 [300 400   5]
 [  0   1   2]]
(3, 3)


In [ ]:
d = np.vstack((c2,b))
print(d)
print(d.shape)

[[  0   1   2]
 [100 200   3]
 [300 400   5]]
(3, 3)


In [ ]:
# hsplit
a = np.array([100,200, 3,300,400, 5,8,9,10,15,20,20])
b = a.reshape(3,4)
print(b)

[[100 200   3 300]
 [400   5   8   9]
 [ 10  15  20  20]]


In [ ]:
b1, b2 = np.hsplit(b,2)
print(b2)

[[  3 300]
 [  8   9]
 [ 20  20]]


In [ ]:
b1, b2, b3, b4 = np.hsplit(b,4)
print(b1)

[[100]
 [400]
 [ 10]]


In [ ]:
# vsplit
b1, b2, b3 = np.vsplit(b, 3)
print(b1)

[[100 200   3 300]]


In [ ]:
# view dan copy
a = np.array([100,200, 3,300,400, 5,8,9,10,15,20,20])
b = a.reshape(3,4)
print(b)

[[100 200   3 300]
 [400   5   8   9]
 [ 10  15  20  20]]


In [ ]:
b_view = b.view()
b_copy = b.copy()

In [ ]:
print(b_view)
print(b_copy)

[[100 200   3 300]
 [400   5   8   9]
 [ 10  15  20  20]]
[[100 200   3 300]
 [400   5   8   9]
 [ 10  15  20  20]]


In [ ]:
b[0,0] = 1
print(b)

[[  1 200   3 300]
 [400   5   8   9]
 [ 10  15  20  20]]


In [ ]:
print(b_view)
print(b_copy)

[[  1 200   3 300]
 [400   5   8   9]
 [ 10  15  20  20]]
[[100 200   3 300]
 [400   5   8   9]
 [ 10  15  20  20]]


In [ ]:
b_view[0,1] = 50
print(b_view)

[[  1  50   3 300]
 [400   5   8   9]
 [ 10  15  20  20]]


In [ ]:
print(b)

[[  1  50   3 300]
 [400   5   8   9]
 [ 10  15  20  20]]


In [ ]:
print(b_copy)

[[100 200   3 300]
 [400   5   8   9]
 [ 10  15  20  20]]


# Operations

In [ ]:
a = np.array([100,200, 3,300,400, 5,8,9,10,15,20,20])
b = a.reshape(3,4)
print(b)

[[100 200   3 300]
 [400   5   8   9]
 [ 10  15  20  20]]


In [ ]:
b * 2

array([[200, 400,   6, 600],
       [800,  10,  16,  18],
       [ 20,  30,  40,  40]])

In [ ]:
b / 100

array([[1.  , 2.  , 0.03, 3.  ],
       [4.  , 0.05, 0.08, 0.09],
       [0.1 , 0.15, 0.2 , 0.2 ]])

In [ ]:
b + 3 * 2 - 10

array([[ 96, 196,  -1, 296],
       [396,   1,   4,   5],
       [  6,  11,  16,  16]])

In [ ]:
b % 2

array([[0, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 0, 0]], dtype=int32)

In [ ]:
a = np.arange(6).reshape(2,3)
b = np.arange(10,16).reshape(2,3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]


In [ ]:
a + b

array([[10, 12, 14],
       [16, 18, 20]])

In [ ]:
a * b

array([[ 0, 11, 24],
       [39, 56, 75]])

In [ ]:
a = np.arange(6).reshape(2,3)
b = np.arange(10,16).reshape(3,2)
print(a)
print(b)
# karena bentuknya beda, kalau a + b langsung error

[[0 1 2]
 [3 4 5]]
[[10 11]
 [12 13]
 [14 15]]


# Operations lainnya
- max
- min
- sum
- mean

In [ ]:
a = np.array([100,200, 3,300,400, 5,8,9,10,15,20,20])
b = a.reshape(3,4)
print(b)

[[100 200   3 300]
 [400   5   8   9]
 [ 10  15  20  20]]


In [ ]:
b.max()

400

In [ ]:
b.max(axis=0) # baris1, baris2, baris3, yang angka paling besar siapa

array([400, 200,  20, 300])

In [ ]:
b.max(axis=1)# kolom1, kolom2, kolom3, kolom4, yang angka paling besar siapa

array([300, 400,  20])

In [ ]:
print(b.min())
print(b.min(axis=0))
print(b.min(axis=1))

3
[10  5  3  9]
[ 3  5 10]


In [ ]:
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

1090
[510 220  31 329]
[603 422  65]


In [ ]:
print(b.mean())
print(b.mean(axis=0)) # semua baris gabung jadi sisa 1 baris
print(b.mean(axis=1)) # semua kolom  gabung jadi sisa 1 kolom

90.83333333333333
[170.          73.33333333  10.33333333 109.66666667]
[150.75 105.5   16.25]


# Matrices
numpy array 2 dimensi isinya angka semua, dan seimbang

# Flatten
mengubah array menjadi 1 dimensi
- flatten (mirip copy)
- ravel (mirip view)

In [ ]:
a_flat = a.flatten()
a_ravel= a.ravel()

In [ ]:
print(a_flat)
print(a_ravel)

[100 200   3 300 400   5   8   9  10  15  20  20]
[100 200   3 300 400   5   8   9  10  15  20  20]


In [ ]:
a[0,0] = -5
print(a)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
print(a_flat)
print(a_ravel)

[100 200   3 300 400   5   8   9  10  15  20  20]
[100 200   3 300 400   5   8   9  10  15  20  20]
